-- LOG660 - Laboratoire 4 - Point 1
-- ETL : extraction des donnees Webflix, transformation dimensionnelle,
-- generation de locations synthetiques et chargement du schema en etoile.
-- Prerequis : executer 01_schema_etoile.sql.

SET SERVEROUTPUT ON;
SET DEFINE OFF;

-- Le script est rejouable : vider d'abord les objets de l'entrepot.
DELETE FROM DW_FAIT_LOCATION;
DELETE FROM DW_STG_LOCATION;
DELETE FROM DW_DIM_CLIENT;
DELETE FROM DW_DIM_FILM;
DELETE FROM DW_DIM_TEMPS;
COMMIT;

PROMPT 1/5 - Extraction et chargement de la dimension Film...

INSERT INTO DW_DIM_FILM (
    FILM_ID_SOURCE, TITRE_COMPLET, ANNEE_SORTIE, ORIGINE,
    GENRE_ACTION, GENRE_ADVENTURE, GENRE_ANIMATION, GENRE_BIOGRAPHY,
    GENRE_COMEDY, GENRE_CRIME, GENRE_DOCUMENTARY, GENRE_DRAMA,
    GENRE_FAMILY, GENRE_FANTASY, GENRE_FILM_NOIR, GENRE_HISTORY,
    GENRE_HORROR, GENRE_MUSIC, GENRE_MUSICAL, GENRE_MYSTERY,
    GENRE_ROMANCE, GENRE_SCI_FI, GENRE_SPORT, GENRE_THRILLER,
    GENRE_WAR, GENRE_WESTERN
)
SELECT
    F.ID,
    F.TITRE,
    F.ANNEE,
    CASE
        WHEN MAX(CASE
            WHEN UPPER(TRIM(P.NOM_PAYS)) IN
                 ('USA', 'UNITED STATES', 'UNITED STATES OF AMERICA',
                  'ETATS-UNIS', 'ÉTATS-UNIS')
              OR UPPER(TRIM(P.NOM_PAYS)) LIKE '%UNITED STATES%'
            THEN 1 ELSE 0 END) = 1
        THEN 'USA'
        ELSE 'AUTRE'
    END AS ORIGINE,
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'ACTION'       THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'ADVENTURE'    THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'ANIMATION'    THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'BIOGRAPHY'    THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'COMEDY'       THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'CRIME'        THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'DOCUMENTARY'  THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'DRAMA'        THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'FAMILY'       THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'FANTASY'      THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) IN ('FILM-NOIR', 'FILM NOIR')
             THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'HISTORY'      THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'HORROR'       THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'MUSIC'        THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'MUSICAL'      THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'MYSTERY'      THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'ROMANCE'      THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) IN
                  ('SCI-FI', 'SCI FI', 'SCIENCE FICTION')
             THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'SPORT'        THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'THRILLER'     THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'WAR'          THEN 1 ELSE 0 END),
    MAX(CASE WHEN UPPER(TRIM(G.NOM_GENRE)) = 'WESTERN'      THEN 1 ELSE 0 END)
FROM FILM F
LEFT JOIN FILM_GENRE FG
       ON FG.FILM_ID = F.ID
LEFT JOIN GENRE G
       ON G.ID_GENRE = FG.GENRE_ID
LEFT JOIN FILM_PAYS_PRODUCTION FPP
       ON FPP.FILM_ID = F.ID
LEFT JOIN PAYS P
       ON P.ID = FPP.PAYS_ID
GROUP BY F.ID, F.TITRE, F.ANNEE;

COMMIT;

PROMPT 2/5 - Generation reproductible des locations synthetiques...

DECLARE
    TYPE T_FILM_IDS IS TABLE OF NUMBER;
    V_FILM_IDS       T_FILM_IDS;
    V_NB_LOCATIONS   PLS_INTEGER;
    V_FILM_INDEX     PLS_INTEGER;
    V_DATE_DEBUT     DATE := ADD_MONTHS(TRUNC(SYSDATE), -36);
    V_DATE_LOCATION  DATE;
    V_STAGE_COUNT    PLS_INTEGER;
BEGIN
    SELECT FILM_ID_SOURCE
    BULK COLLECT INTO V_FILM_IDS
    FROM DW_DIM_FILM
    ORDER BY FILM_ID_SOURCE;

    IF V_FILM_IDS.COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Aucun film n''a ete charge dans DW_DIM_FILM.');
    END IF;

    -- Graine fixe : deux executions produisent la meme distribution generale.
    DBMS_RANDOM.SEED(660405);

    FOR C IN (SELECT ID_CLIENT FROM CLIENT ORDER BY ID_CLIENT) LOOP
        -- De 5 a 20 films loues par client.
        V_NB_LOCATIONS := TRUNC(DBMS_RANDOM.VALUE(5, 21));

        FOR I IN 1 .. V_NB_LOCATIONS LOOP
            V_FILM_INDEX := TRUNC(DBMS_RANDOM.VALUE(1, V_FILM_IDS.COUNT + 1));
            V_DATE_LOCATION := V_DATE_DEBUT
                + DBMS_RANDOM.VALUE(0, SYSDATE - V_DATE_DEBUT);

            INSERT INTO DW_STG_LOCATION (
                CLIENT_ID_SOURCE, FILM_ID_SOURCE, DATE_LOCATION
            ) VALUES (
                C.ID_CLIENT,
                V_FILM_IDS(V_FILM_INDEX),
                V_DATE_LOCATION
            );
        END LOOP;
    END LOOP;

    COMMIT;
    SELECT COUNT(*) INTO V_STAGE_COUNT FROM DW_STG_LOCATION;
    DBMS_OUTPUT.PUT_LINE(V_STAGE_COUNT ||
        ' locations synthetiques generees dans DW_STG_LOCATION.');
END;
/

PROMPT 3/5 - Transformation et chargement de la dimension Client...

INSERT INTO DW_DIM_CLIENT (
    CLIENT_ID_SOURCE, NOM_COMPLET, AGE_ANNEES, AGE_MIN_GROUPE,
    GROUPE_AGE, DATE_PREMIERE_LOCATION, CODE_POSTAL, VILLE, PROVINCE
)
WITH CLIENTS_SOURCE AS (
    SELECT
        C.ID_CLIENT AS CLIENT_ID_SOURCE,
        TRIM(U.PRENOM || ' ' || NVL(U.NOM, '')) AS NOM_COMPLET,
        CASE
            WHEN U.DATE_NAISSANCE IS NULL THEN NULL
            ELSE TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), U.DATE_NAISSANCE) / 12)
        END AS AGE_ANNEES,
        A.CODE_POSTAL,
        A.VILLE,
        A.PROVINCE
    FROM CLIENT C
    JOIN UTILISATEUR U
      ON U.ID = C.ID_CLIENT
    JOIN ADRESSE A
      ON A.ID_ADRESSE = C.ADRESSE_ID
), PREMIERES_LOCATIONS AS (
    SELECT CLIENT_ID_SOURCE, MIN(DATE_LOCATION) AS DATE_PREMIERE_LOCATION
    FROM DW_STG_LOCATION
    GROUP BY CLIENT_ID_SOURCE
)
SELECT
    CS.CLIENT_ID_SOURCE,
    CS.NOM_COMPLET,
    CS.AGE_ANNEES,
    CASE
        WHEN CS.AGE_ANNEES IS NULL THEN NULL
        ELSE TRUNC(CS.AGE_ANNEES / 5) * 5
    END AS AGE_MIN_GROUPE,
    CASE
        WHEN CS.AGE_ANNEES IS NULL THEN 'Inconnu'
        ELSE TO_CHAR(TRUNC(CS.AGE_ANNEES / 5) * 5)
             || '-'
             || TO_CHAR(TRUNC(CS.AGE_ANNEES / 5) * 5 + 4)
    END AS GROUPE_AGE,
    PL.DATE_PREMIERE_LOCATION,
    CS.CODE_POSTAL,
    CS.VILLE,
    CS.PROVINCE
FROM CLIENTS_SOURCE CS
LEFT JOIN PREMIERES_LOCATIONS PL
       ON PL.CLIENT_ID_SOURCE = CS.CLIENT_ID_SOURCE;

COMMIT;

PROMPT 4/5 - Transformation et chargement de la dimension Temps...

INSERT INTO DW_DIM_TEMPS (
    DATE_COMPLETE, HEURE, JOUR_SEMAINE, NUM_JOUR_SEMAINE,
    MOIS_ANNEE, NUM_MOIS, ANNEE
)
SELECT DISTINCT
    TRUNC(S.DATE_LOCATION) AS DATE_COMPLETE,
    TO_NUMBER(TO_CHAR(S.DATE_LOCATION, 'HH24')) AS HEURE,
    INITCAP(TRIM(TO_CHAR(
        S.DATE_LOCATION, 'FMDay', 'NLS_DATE_LANGUAGE=English'
    ))) AS JOUR_SEMAINE,
    1 + TRUNC(S.DATE_LOCATION) - TRUNC(S.DATE_LOCATION, 'IW')
        AS NUM_JOUR_SEMAINE,
    INITCAP(TRIM(TO_CHAR(
        S.DATE_LOCATION, 'FMMonth', 'NLS_DATE_LANGUAGE=English'
    ))) AS MOIS_ANNEE,
    TO_NUMBER(TO_CHAR(S.DATE_LOCATION, 'MM')) AS NUM_MOIS,
    TO_NUMBER(TO_CHAR(S.DATE_LOCATION, 'YYYY')) AS ANNEE
FROM DW_STG_LOCATION S;

COMMIT;

PROMPT 5/5 - Chargement de la table de faits...

INSERT INTO DW_FAIT_LOCATION (
    CLIENT_KEY, FILM_KEY, TEMPS_KEY, NOMBRE_LOCATIONS
)
SELECT
    DC.CLIENT_KEY,
    DF.FILM_KEY,
    DT.TEMPS_KEY,
    1
FROM DW_STG_LOCATION S
JOIN DW_DIM_CLIENT DC
  ON DC.CLIENT_ID_SOURCE = S.CLIENT_ID_SOURCE
JOIN DW_DIM_FILM DF
  ON DF.FILM_ID_SOURCE = S.FILM_ID_SOURCE
JOIN DW_DIM_TEMPS DT
  ON DT.DATE_COMPLETE = TRUNC(S.DATE_LOCATION)
 AND DT.HEURE = TO_NUMBER(TO_CHAR(S.DATE_LOCATION, 'HH24'));

COMMIT;

PROMPT ETL termine. Executer 03_requetes_validation.sql pour les preuves.
