-- LOG660 - Laboratoire 4 - Point 1
-- Requetes de validation et exemples a capturer dans SQL Developer.

SET LINESIZE 220;
SET PAGESIZE 100;

PROMPT === Volumetrie de l'entrepot ===
SELECT 'DW_DIM_CLIENT' TABLE_NAME, COUNT(*) NB_LIGNES FROM DW_DIM_CLIENT
UNION ALL
SELECT 'DW_DIM_FILM', COUNT(*) FROM DW_DIM_FILM
UNION ALL
SELECT 'DW_DIM_TEMPS', COUNT(*) FROM DW_DIM_TEMPS
UNION ALL
SELECT 'DW_FAIT_LOCATION', COUNT(*) FROM DW_FAIT_LOCATION
UNION ALL
SELECT 'DW_STG_LOCATION', COUNT(*) FROM DW_STG_LOCATION;

PROMPT === Verification du grain et de la metrique additive ===
SELECT COUNT(*) AS NB_LIGNES_FAIT,
       SUM(NOMBRE_LOCATIONS) AS NB_TOTAL_LOCATIONS
FROM DW_FAIT_LOCATION;

PROMPT === Echantillon complet de cinq faits ===
SELECT *
FROM (
    SELECT
        F.LOCATION_KEY,
        C.NOM_COMPLET,
        C.GROUPE_AGE,
        C.PROVINCE,
        FI.TITRE_COMPLET,
        T.DATE_COMPLETE,
        T.HEURE,
        T.JOUR_SEMAINE,
        T.MOIS_ANNEE,
        F.NOMBRE_LOCATIONS
    FROM DW_FAIT_LOCATION F
    JOIN DW_DIM_CLIENT C ON C.CLIENT_KEY = F.CLIENT_KEY
    JOIN DW_DIM_FILM FI ON FI.FILM_KEY = F.FILM_KEY
    JOIN DW_DIM_TEMPS T ON T.TEMPS_KEY = F.TEMPS_KEY
    ORDER BY F.LOCATION_KEY
)
WHERE ROWNUM <= 5;

PROMPT === Distribution par groupe d'age ===
SELECT C.GROUPE_AGE, SUM(F.NOMBRE_LOCATIONS) NB_LOCATIONS
FROM DW_FAIT_LOCATION F
JOIN DW_DIM_CLIENT C ON C.CLIENT_KEY = F.CLIENT_KEY
GROUP BY C.GROUPE_AGE, C.AGE_MIN_GROUPE
ORDER BY C.AGE_MIN_GROUPE NULLS LAST;

PROMPT === Distribution par province ===
SELECT C.PROVINCE, SUM(F.NOMBRE_LOCATIONS) NB_LOCATIONS
FROM DW_FAIT_LOCATION F
JOIN DW_DIM_CLIENT C ON C.CLIENT_KEY = F.CLIENT_KEY
GROUP BY C.PROVINCE
ORDER BY C.PROVINCE;

PROMPT === Distribution par jour de semaine ===
SELECT T.JOUR_SEMAINE, SUM(F.NOMBRE_LOCATIONS) NB_LOCATIONS
FROM DW_FAIT_LOCATION F
JOIN DW_DIM_TEMPS T ON T.TEMPS_KEY = F.TEMPS_KEY
GROUP BY T.JOUR_SEMAINE, T.NUM_JOUR_SEMAINE
ORDER BY T.NUM_JOUR_SEMAINE;

PROMPT === Distribution par mois ===
SELECT T.MOIS_ANNEE, SUM(F.NOMBRE_LOCATIONS) NB_LOCATIONS
FROM DW_FAIT_LOCATION F
JOIN DW_DIM_TEMPS T ON T.TEMPS_KEY = F.TEMPS_KEY
GROUP BY T.MOIS_ANNEE, T.NUM_MOIS
ORDER BY T.NUM_MOIS;

PROMPT === Exemple demande : Tous, QC, Tous, April ===
SELECT SUM(F.NOMBRE_LOCATIONS) AS NB_LOCATIONS
FROM DW_FAIT_LOCATION F
JOIN DW_DIM_CLIENT C ON C.CLIENT_KEY = F.CLIENT_KEY
JOIN DW_DIM_TEMPS T ON T.TEMPS_KEY = F.TEMPS_KEY
WHERE UPPER(C.PROVINCE) = 'QC'
  AND T.MOIS_ANNEE = 'April';

PROMPT === Requete parametree utilisee par l'application ===
-- Dans SQL Developer, remplacer les valeurs des quatre variables au besoin.
VAR P_GROUPE_AGE VARCHAR2(20);
VAR P_PROVINCE VARCHAR2(100);
VAR P_JOUR_SEMAINE VARCHAR2(12);
VAR P_MOIS_ANNEE VARCHAR2(12);

EXEC :P_GROUPE_AGE := 'Tous';
EXEC :P_PROVINCE := 'QC';
EXEC :P_JOUR_SEMAINE := 'Tous';
EXEC :P_MOIS_ANNEE := 'April';

SELECT COALESCE(SUM(F.NOMBRE_LOCATIONS), 0) AS NB_LOCATIONS
FROM DW_FAIT_LOCATION F
JOIN DW_DIM_CLIENT C ON C.CLIENT_KEY = F.CLIENT_KEY
JOIN DW_DIM_TEMPS T ON T.TEMPS_KEY = F.TEMPS_KEY
WHERE (:P_GROUPE_AGE = 'Tous' OR C.GROUPE_AGE = :P_GROUPE_AGE)
  AND (:P_PROVINCE = 'Tous' OR C.PROVINCE = :P_PROVINCE)
  AND (:P_JOUR_SEMAINE = 'Tous' OR T.JOUR_SEMAINE = :P_JOUR_SEMAINE)
  AND (:P_MOIS_ANNEE = 'Tous' OR T.MOIS_ANNEE = :P_MOIS_ANNEE);
